name: Punish
version: '${project.version}'
main: chips.punish.Punish
api-version: '1.20'
commands:
    punish:
        description: Punishes a player
        usage: /<command> <player>
        permission: punish.command